name: Build Project

on:
  push:
    paths:
      - 'src/**'
      - 'pom.xml'

jobs:
  verify:
    name: Verify project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Verify with Maven
      run: ./mvnw --batch-mode --update-snapshots verify