name: Deploy Javadoc

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots verify
    - name: Generate JavaDoc
      run: mvn javadoc:javadoc
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.2.2
      with:
        BRANCH: gh-pages
        CLEAN: true
        FOLDER: target/site/apidocs
        TARGET_FOLDER: javadoc
