name: Development Build

on:
  push:
    branches:
      - develop
    paths:
      - src/**
      - pom.xml
      - simulator-example.properties
      
jobs:
  verify:
    name: Verify project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    - name: Verify with Maven
      run: mvn --batch-mode --update-snapshots verify
      
  properties:
    needs: verify
    name: Publish simulator properties
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Upload Properties
      uses: svenstaro/upload-release-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: simulator-example.properties
        asset_name: simulator.properties
        prerelease: true
        overwrite: true
        tag: development
        release_name: Automatic Development Build
        body: This release is an automatic build from the develop branch.
  publish:
    needs: verify
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: RobbiSimulator.jar
            asset_name: RobbiSimulator-Linux.jar
          - os: windows-latest
            artifact_name: RobbiSimulator.jar
            asset_name: RobbiSimulator-Win.jar
          - os: macos-latest
            artifact_name: RobbiSimulator.jar
            asset_name: RobbiSimulator-Mac.jar
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    - name: Generate Jar
      run: |
        mvn --batch-mode --update-snapshots clean install package
    - name: Upload Application
      uses: svenstaro/upload-release-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        prerelease: true
        overwrite: true
        tag: development
        release_name: Automatic Development Build
        body: This release is an automatic build from the develop branch.
