name: pre-release

on:
  push:
    branches:
      - main
      
jobs:
  pre-release:
    name: "Pre Release"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots verify
    - name: Generate Jar
      run: |
        mvn clean install package
    - uses: "marvinpinto/action-automatic-releases@latest"        
      with: 
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Pre-release Build"
        files: |
          target/*.jar
